//! Provider cost rate table — bundled + runtime-override support.
//!
//! ## Purpose
//!
//! Provides `ProviderRates` (deserialized from `monitoring/provider-rates.toml`)
//! and the `PROVIDER_RATES` global registry. Cost-aware wrappers (e.g.
//! `TokenTrackingChatProvider`) call `PROVIDER_RATES.get()` and
//! `lookup_rate()` to look up the per-1k-token USD rate for a given
//! `(provider, model)` pair and emit `kremory_core_cost_usd_total` gauges.
//! Callers that already have separate input/output token counts (e.g.
//! dream-pass budget tracking) use `cost_usd()` instead, which prefers
//! per-direction rates when the matched entry has them (this
//! is the single source of truth for provider cost; the previous duplicate,
//! `anthropic_rate_per_token` in `core/ingest/mod.rs`, has been deleted).
//!
//! ## Data provenance
//!
//! The bundled `monitoring/provider-rates.toml` is SSOT-derived, not
//! hand-typed: it is generated by `monitoring/refresh-provider-rates.py` from
//! [LiteLLM's `model_prices_and_context_window.json`](https://github.com/BerriAI/litellm)
//! (MIT-licensed, updated daily). Re-run that script to refresh rates rather
//! than hand-editing the toml — hand-edits drift from the SSOT silently and
//! desync `rates_as_of` (asserted in `provider_rates_bundled_defaults_load`
//! below). Entries absent from the SSOT (local/self-hosted models) are
//! preserved verbatim by the script rather than dropped.
//!
//! ## Initialization
//!
//! Call `init_bundled()` once at startup (idempotent — second call is a no-op)
//! to load the rates bundled at compile time. Use `init_from_path()` if the
//! caller wants to supply an updated rates file at runtime.
//!
//! ## TOML schema (monitoring/provider-rates.toml)
//!
//! ```toml
//! rates_as_of = "YYYY-MM-DD"
//!
//! [[providers]]
//! provider = "openai"
//! model    = "gpt-4o"
//! cost_per_1k_tokens_usd = 0.01
//!
//! [[providers]]
//! provider = "anthropic"
//! model    = "claude-sonnet-4-6"
//! cost_per_1k_tokens_usd = 0.015          # single-rate fallback (output rate)
//! cost_per_1k_input_tokens_usd = 0.003    # optional — enables per-direction cost_usd()
//! cost_per_1k_output_tokens_usd = 0.015   # optional
//! ```
//!
//! `cost_per_1k_input_tokens_usd` / `cost_per_1k_output_tokens_usd` are
//! optional. `lookup_rate()` always uses `cost_per_1k_tokens_usd` (no
//! direction concept). `cost_usd()` uses the per-direction fields when both
//! are present, else falls back to `cost_per_1k_tokens_usd` for both
//! directions. For chat models the single-rate fallback is conventionally
//! the output rate (more conservative / expensive).

use std::path::Path;
use std::sync::OnceLock;

use serde::Deserialize;

/// Global provider rate table. Initialized once via `init_bundled()` or
/// `init_from_path()`. Reads are lock-free after initialization.
pub static PROVIDER_RATES: OnceLock<ProviderRates> = OnceLock::new();

/// Deserialized contents of `monitoring/provider-rates.toml`.
#[derive(Debug, Clone, Deserialize)]
pub struct ProviderRates {
    /// ISO-8601 date string indicating when these rates were last verified.
    pub rates_as_of: String,
    /// All rate entries across providers/models.
    pub providers: Vec<ProviderRateEntry>,
}

/// A single rate entry in the provider-rates table.
///
/// Re-exported via `kremory::observability` (spec line 457).
#[derive(Debug, Clone, Deserialize)]
pub struct ProviderRateEntry {
    /// Provider identifier (e.g. `"openai"`, `"anthropic"`, `"voyage"`).
    pub provider: String,
    /// Model identifier (e.g. `"gpt-4o"`, `"claude-haiku-4-5"`).
    /// Use `"*"` as a wildcard for all models of a provider (e.g. Ollama).
    pub model: String,
    /// USD cost per 1,000 tokens — single-rate fallback used when
    /// per-direction rates below are absent, and by [`ProviderRates::lookup_rate`]
    /// (which has no direction concept). For chat models this is
    /// conventionally the output rate (more conservative / expensive).
    pub cost_per_1k_tokens_usd: f64,
    /// Embedding dimension count (only relevant for embedding models).
    #[serde(default)]
    pub dimensions: Option<u32>,
    /// USD cost per 1,000 INPUT tokens. `None` for entries that
    /// only carry a single blended rate — [`ProviderRates::cost_usd`] falls
    /// back to `cost_per_1k_tokens_usd` for both directions in that case.
    #[serde(default)]
    pub cost_per_1k_input_tokens_usd: Option<f64>,
    /// USD cost per 1,000 OUTPUT tokens. See
    /// `cost_per_1k_input_tokens_usd`.
    #[serde(default)]
    pub cost_per_1k_output_tokens_usd: Option<f64>,
}

/// Bundled parameters for [`ProviderRates::cost_usd`] — args-as-object to
/// keep the function under clippy's `too_many_arguments` threshold (mirrors
/// `ComputeDreamCostMicroParams` in `core/ingest/mod.rs`).
pub struct CostUsdParams<'a> {
    pub provider: &'a str,
    pub model: &'a str,
    pub tokens_input: u64,
    pub tokens_output: u64,
}

impl ProviderRates {
    /// Load bundled rates from `crates/kremory/monitoring/provider-rates.toml`
    /// (compile-time `include_str!`). The path is relative to this source file:
    /// `crates/kremory/src/core/rates.rs` → 2 levels up → `crates/kremory/` →
    /// `monitoring/provider-rates.toml`. The TOML lives INSIDE the published
    /// crate so the bundled rates ship with `cargo publish`.
    pub fn from_bundled() -> Result<Self, RatesError> {
        const BUNDLED: &str = include_str!("../../monitoring/provider-rates.toml");
        toml::from_str(BUNDLED).map_err(RatesError::Parse)
    }

    /// Load rates from a user-specified path at runtime.
    ///
    /// # Errors
    ///
    /// Returns `RatesError::Io` if the file cannot be read, or
    /// `RatesError::Parse` if the TOML is malformed.
    pub fn from_path(path: &Path) -> Result<Self, RatesError> {
        let content = std::fs::read_to_string(path).map_err(RatesError::Io)?;
        toml::from_str(&content).map_err(RatesError::Parse)
    }

    /// Look up the USD cost per 1k tokens for a `(provider, model)` pair.
    ///
    /// - Matches exact `provider` + `model` first.
    /// - Falls back to a prefix match (see [`ProviderRates::find_entry`]).
    /// - Falls back to `provider` + `"*"` (wildcard model) if neither matches.
    ///
    /// Returns `None` if no matching entry exists in the table.
    pub fn lookup_rate(&self, provider: &str, model: &str) -> Option<f64> {
        self.find_entry(provider, model)
            .map(|r| r.cost_per_1k_tokens_usd)
    }

    /// Compute the USD cost for a `(provider, model)` pair given
    /// per-direction token counts (replaces the duplicate
    /// hand-rolled `anthropic_rate_per_token` table formerly in
    /// `core/ingest/mod.rs`).
    ///
    /// Entry resolution is [`ProviderRates::find_entry`] (exact → prefix →
    /// wildcard). When the matched entry carries both
    /// `cost_per_1k_input_tokens_usd` and `cost_per_1k_output_tokens_usd`,
    /// those rates are used per direction. Otherwise falls back to
    /// `cost_per_1k_tokens_usd` for BOTH directions — identical to the
    /// pre-C5a single-rate behavior, so single-rate entries see no precision
    /// change.
    ///
    /// Returns `None` if no entry matches (unknown model → caller writes
    /// NULL rather than a silently-wrong cost).
    pub fn cost_usd(&self, params: CostUsdParams<'_>) -> Option<f64> {
        let CostUsdParams {
            provider,
            model,
            tokens_input,
            tokens_output,
        } = params;
        let entry = self.find_entry(provider, model)?;
        let (input_rate, output_rate) = match (
            entry.cost_per_1k_input_tokens_usd,
            entry.cost_per_1k_output_tokens_usd,
        ) {
            (Some(input_rate), Some(output_rate)) => (input_rate, output_rate),
            _ => (entry.cost_per_1k_tokens_usd, entry.cost_per_1k_tokens_usd),
        };
        let cost = (tokens_input as f64 / 1000.0) * input_rate
            + (tokens_output as f64 / 1000.0) * output_rate;
        Some(cost)
    }

    /// Shared entry-resolution logic for [`ProviderRates::lookup_rate`] and
    /// [`ProviderRates::cost_usd`].
    ///
    /// 1. Exact `provider` + `model` match.
    /// 2. Longest same-provider entry whose `model` is a PREFIX of the
    ///    queried `model`, restricted to a VERSION/DATE-SUFFIXED remainder
    ///    (see [`is_version_suffix`]; covers date-suffixed API model ids,
    ///    e.g. the Anthropic wire id `claude-haiku-4-5-20251001` matches the
    ///    toml entry `claude-haiku-4-5`). Wildcard (`"*"`) entries are
    ///    excluded from this step — they're handled explicitly in step 3.
    /// 3. `provider` + `"*"` wildcard (e.g. `ollama/*`).
    ///
    /// New Anthropic model generations need their own toml entry rather than
    /// an open family-wide prefix (e.g. `"claude-haiku-"`) — an open prefix
    /// would also become the EXACT label `chat_tracking`/`embedding` use for
    /// metric attribution, colliding with their exact-match contract.
    fn find_entry(&self, provider: &str, model: &str) -> Option<&ProviderRateEntry> {
        if let Some(r) = self
            .providers
            .iter()
            .find(|r| r.provider == provider && r.model == model)
        {
            return Some(r);
        }
        if let Some(r) = self
            .providers
            .iter()
            .filter(|r| {
                r.provider == provider
                    && r.model != "*"
                    && model
                        .strip_prefix(r.model.as_str())
                        .is_some_and(is_version_suffix)
            })
            .max_by_key(|r| r.model.len())
        {
            return Some(r);
        }
        self.providers
            .iter()
            .find(|r| r.provider == provider && r.model == "*")
    }
}

/// True when `remainder` — the suffix of a queried model id left over after
/// stripping a candidate toml entry's `model` prefix — marks a version/date
/// suffix of the SAME model rather than a DIFFERENT model that merely shares
/// a name prefix (parse/lookup loud, never silently inherit a
/// sibling model's rate).
///
/// A version/date suffix always starts with `-` immediately followed by an
/// ASCII digit (e.g. `-20251001`, `-2024-05-13`, `-4-5-20250101` for the
/// Anthropic wire ids `claude-haiku-4-5-20251001` etc.). A remainder that
/// starts with `-` followed by a LETTER (e.g. `-realtime-preview`,
/// `-vision`) names a distinct model variant sharing the family's prefix —
/// `find_entry` must NOT treat that as a match; the lookup falls through to
/// the wildcard step or returns `None` instead of silently mis-pricing an
/// unlisted variant at its neighbour's rate.
fn is_version_suffix(remainder: &str) -> bool {
    let mut chars = remainder.chars();
    matches!(chars.next(), Some('-')) && matches!(chars.next(), Some(c) if c.is_ascii_digit())
}

/// Initialize `PROVIDER_RATES` from the bundled TOML. Idempotent — a second
/// call is a no-op (the `OnceLock` value is already set).
///
/// # Errors
///
/// Returns `RatesError::Parse` if the bundled TOML fails to deserialize.
/// This indicates a compile-time asset issue and is unlikely in practice.
pub fn init_bundled() -> Result<(), RatesError> {
    let rates = ProviderRates::from_bundled()?;
    // OnceLock::set returns Err(value) if already set — we intentionally discard it.
    let _ = PROVIDER_RATES.set(rates);
    Ok(())
}

/// Initialize `PROVIDER_RATES` from a user-supplied file path at runtime.
/// Idempotent — a second call is a no-op.
///
/// # Errors
///
/// Returns `RatesError::Io` or `RatesError::Parse` if the file cannot be
/// read or parsed.
pub fn init_from_path(path: &Path) -> Result<(), RatesError> {
    let rates = ProviderRates::from_path(path)?;
    let _ = PROVIDER_RATES.set(rates);
    Ok(())
}

/// Errors that can occur when loading a rates table.
#[derive(Debug, thiserror::Error)]
pub enum RatesError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("toml parse: {0}")]
    Parse(#[from] toml::de::Error),
}

// ── Unit tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;

    // ── G_v012_4: provider_rates_bundled_defaults_load ───────────────────────

    /// G_v012_4 — Parse bundled rates TOML; assert `rates_as_of` matches the
    /// committed date and spot-check known rates for 3 embedder models and 5
    /// chat model entries.
    #[test]
    fn provider_rates_bundled_defaults_load() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        assert_eq!(
            rates.rates_as_of, "2026-07-21",
            "rates_as_of must match the committed date (bumped by \
             monitoring/refresh-provider-rates.py, which regenerates this file from the \
             LiteLLM pricing SSOT; re-run that script rather than hand-editing this date)"
        );

        // ── Embedder spot-checks ─────────────────────────────────────────────
        let embedder_cases: &[(&str, &str)] = &[
            ("openai", "text-embedding-3-small"),
            ("voyage", "voyage-3"),
            ("local", "all-minilm-l6-v2"),
        ];
        for &(provider, model) in embedder_cases {
            assert!(
                rates.lookup_rate(provider, model).is_some(),
                "embedder rate for {provider}/{model} must exist in bundled TOML"
            );
        }

        // ── Chat spot-checks (2-arg lookup) ──────────────────────────────────
        let chat_cases: &[(&str, &str)] = &[
            ("openai", "gpt-4o-mini"),
            ("openai", "gpt-4o"),
            ("anthropic", "claude-haiku-4-5"),
            ("anthropic", "claude-sonnet-4-6"),
            ("ollama", "any-model"),
        ];
        for &(provider, model) in chat_cases {
            assert!(
                rates.lookup_rate(provider, model).is_some(),
                "chat rate for {provider}/{model} must exist in bundled TOML"
            );
        }
    }

    // ── G_v012_5: lookup_rate_unknown_provider_returns_none ──────────────────

    /// G_v012_5 — `lookup_rate` for a nonexistent provider/model pair must
    /// return `None` (no panics, no partial matches).
    #[test]
    fn lookup_rate_unknown_provider_returns_none() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        assert_eq!(
            rates.lookup_rate("nonexistent", "x"),
            None,
            "lookup_rate for unknown provider must return None"
        );
        assert_eq!(
            rates.lookup_rate("openai", "nonexistent-model"),
            None,
            "lookup_rate for known provider but unknown model must return None"
        );
    }

    // ── cost_usd per-direction + fallback ─────────────────────────

    /// A per-direction entry (anthropic sonnet) must weight input and output
    /// tokens by their OWN rate, not double-charge one direction. Regression
    /// guard for the exact bug class this refactor eliminates: `1000 in +
    /// 1000 out` must NOT equal `2 * output_rate * 1000`.
    #[test]
    fn cost_usd_per_direction_entry_weights_input_and_output_separately() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        // claude-sonnet-4-6: $3.00/M in ($0.003/1k), $15.00/M out ($0.015/1k).
        let cost = rates
            .cost_usd(CostUsdParams {
                provider: "anthropic",
                model: "claude-sonnet-4-6",
                tokens_input: 1000,
                tokens_output: 1000,
            })
            .expect("sonnet rate must be present in bundled TOML");

        let expected = 1000_f64 / 1000.0 * 0.003 + 1000_f64 / 1000.0 * 0.015;
        assert!(
            (cost - expected).abs() < 1e-9,
            "expected {expected} (input*0.003 + output*0.015), got {cost}"
        );

        let double_output_only = 2.0 * (1000_f64 / 1000.0 * 0.015);
        assert!(
            (cost - double_output_only).abs() > 1e-9,
            "cost must NOT equal double-counting the output rate for both directions \
             (that's the single-rate bug this method fixes)"
        );
    }

    /// A single-rate-only entry (no `cost_per_1k_input_tokens_usd` /
    /// `cost_per_1k_output_tokens_usd` set) must use `cost_per_1k_tokens_usd`
    /// for BOTH directions — identical to the pre-C5a behavior, no precision
    /// regression for entries that haven't been upgraded to per-direction.
    #[test]
    fn cost_usd_falls_back_to_single_rate_for_both_directions() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        // openai/gpt-4o-mini has only cost_per_1k_tokens_usd = 0.0006 (no
        // per-direction fields) in the bundled TOML.
        let cost = rates
            .cost_usd(CostUsdParams {
                provider: "openai",
                model: "gpt-4o-mini",
                tokens_input: 200,
                tokens_output: 300,
            })
            .expect("gpt-4o-mini rate must be present in bundled TOML");

        let expected = (200 + 300) as f64 / 1000.0 * 0.0006;
        assert!(
            (cost - expected).abs() < 1e-9,
            "single-rate entry must charge input+output at the same rate; expected \
             {expected}, got {cost}"
        );
    }

    /// `cost_usd` must resolve a date-suffixed Anthropic wire model id (e.g.
    /// `claude-haiku-4-5-20251001`) via the prefix-match fallback against the
    /// versioned toml entry `claude-haiku-4-5` — the same resolution
    /// `compute_dream_cost_micro` depends on.
    #[test]
    fn cost_usd_prefix_matches_date_suffixed_model_id() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        let exact = rates
            .cost_usd(CostUsdParams {
                provider: "anthropic",
                model: "claude-haiku-4-5",
                tokens_input: 1000,
                tokens_output: 1000,
            })
            .expect("exact haiku entry must resolve");
        let suffixed = rates
            .cost_usd(CostUsdParams {
                provider: "anthropic",
                model: "claude-haiku-4-5-20251001",
                tokens_input: 1000,
                tokens_output: 1000,
            })
            .expect("date-suffixed haiku id must resolve via prefix match");

        assert!(
            (exact - suffixed).abs() < 1e-9,
            "prefix-matched entry must yield the same cost as the exact entry"
        );
    }

    /// An unmatched Anthropic model (no exact, no prefix, no wildcard) must
    /// return `None` — never a silently-wrong cost.
    #[test]
    fn cost_usd_unknown_anthropic_model_returns_none() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        assert_eq!(
            rates.cost_usd(CostUsdParams {
                provider: "anthropic",
                model: "claude-mythos-preview",
                tokens_input: 100,
                tokens_output: 50,
            }),
            None,
            "unrecognized claude-* family must return None, not a guessed rate"
        );
    }

    // ── prefix-match discriminator must not mis-price variants ──

    /// A DIFFERENT model that merely shares a name prefix with a listed
    /// family entry (dash followed by a LETTER, e.g. `-realtime-preview`)
    /// must NOT prefix-match `gpt-4o` and silently inherit its rate — it has
    /// no toml entry and no wildcard exists for `openai`, so both
    /// `lookup_rate` and `cost_usd` must return `None` (fail loud —
    /// never a silently-wrong guessed cost).
    #[test]
    fn find_entry_rejects_letter_suffixed_model_variant() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        assert_eq!(
            rates.lookup_rate("openai", "gpt-4o-realtime-preview"),
            None,
            "gpt-4o-realtime-preview must NOT inherit gpt-4o's rate via prefix match"
        );
        assert_eq!(
            rates.cost_usd(CostUsdParams {
                provider: "openai",
                model: "gpt-4o-realtime-preview",
                tokens_input: 100,
                tokens_output: 50,
            }),
            None,
            "gpt-4o-realtime-preview must NOT inherit gpt-4o's rate via prefix match (cost_usd)"
        );
    }

    /// A genuine date-suffixed wire id of a listed family entry (dash
    /// followed by a DIGIT, e.g. `-2024-05-13`) must still prefix-match —
    /// the discriminator must not regress the existing date-suffix
    /// resolution path this design intentionally preserves.
    #[test]
    fn find_entry_still_matches_digit_suffixed_model_variant() {
        let rates = ProviderRates::from_bundled().expect("bundled rates must parse");

        let base = rates
            .lookup_rate("openai", "gpt-4o")
            .expect("gpt-4o entry must be present in bundled TOML");
        let suffixed = rates
            .lookup_rate("openai", "gpt-4o-2024-05-13")
            .expect("date-suffixed gpt-4o id must still resolve via prefix match");
        assert!(
            (base - suffixed).abs() < 1e-9,
            "gpt-4o-2024-05-13 must resolve to the same rate as gpt-4o"
        );

        let cost = rates
            .cost_usd(CostUsdParams {
                provider: "openai",
                model: "gpt-4o-2024-05-13",
                tokens_input: 1000,
                tokens_output: 1000,
            })
            .expect("date-suffixed gpt-4o id must still resolve via prefix match (cost_usd)");
        assert!(cost > 0.0, "date-suffixed match must yield a non-zero cost");
    }
}
